# Generated by Django 4.1 on 2023-11-19 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Analysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_time", models.DateTimeField(auto_now_add=True)),
                (
                    "file_url",
                    models.CharField(default="", max_length=128, verbose_name="路径"),
                ),
                (
                    "file",
                    models.FileField(
                        default="", upload_to="analysis/", verbose_name="解析"
                    ),
                ),
            ],
            options={
                "db_table": "Analysis",
            },
        ),
    ]
