# Generated by Django 4.1 on 2023-12-19 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Analysis", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="analysis",
            name="is_examined",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="analysis",
            name="title",
            field=models.CharField(default="", max_length=128),
        ),
    ]
