# Generated by Django 4.2.4 on 2023-12-23 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Analysis", "0004_alter_analysis_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="analysis",
            name="file",
            field=models.FileField(
                default="", upload_to="analysis/", verbose_name="解析"
            ),
        ),
    ]
