# Generated by Django 4.2.4 on 2023-12-25 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Analysis", "0005_alter_analysis_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="analysis",
            name="works",
            field=models.CharField(default="", max_length=255),
        ),
    ]
