# Generated by Django 4.2.4 on 2023-12-25 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Essay", "0004_remove_author_is_professional_and_more"),
        ("Analysis", "0006_alter_analysis_works"),
    ]

    operations = [
        migrations.AddField(
            model_name="analysis",
            name="open_alex_id",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="analysis",
            name="works",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="works",
                to="Essay.work",
            ),
        ),
    ]
