# Generated by Django 4.2.4 on 2023-12-25 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Analysis", "0007_analysis_open_alex_id_alter_analysis_works"),
    ]

    operations = [
        migrations.RenameField(
            model_name="analysis",
            old_name="open_alex_id",
            new_name="open_alex_id_work",
        ),
    ]
