# Generated by Django 4.2.4 on 2023-11-18 13:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("Analysis", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("Essay", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="CollectionAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_time", models.DateTimeField(auto_now_add=True)),
                (
                    "analysis",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collection_analysis",
                        to="Analysis.analysis",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CollectionWork",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_time", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="ColletionPackage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_time", models.DateTimeField(auto_now_add=True)),
                ("name", models.CharField(default="", max_length=100)),
                ("sum", models.IntegerField(default=0)),
                (
                    "anaylsis",
                    models.ManyToManyField(
                        blank=True,
                        related_name="collection_package_analysis",
                        through="Collection.CollectionAnalysis",
                        to="Analysis.analysis",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "works",
                    models.ManyToManyField(
                        blank=True,
                        related_name="collection_package_work",
                        through="Collection.CollectionWork",
                        to="Essay.work",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="collectionwork",
            name="collection_package",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="collectionpackage_work",
                to="Collection.colletionpackage",
            ),
        ),
        migrations.AddField(
            model_name="collectionwork",
            name="work",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="collection_work",
                to="Essay.work",
            ),
        ),
        migrations.AddField(
            model_name="collectionanalysis",
            name="collection_package",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="collectionpackage_analysis",
                to="Collection.colletionpackage",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="collectionwork", unique_together={("work", "collection_package")},
        ),
        migrations.AlterUniqueTogether(
            name="collectionanalysis",
            unique_together={("analysis", "collection_package")},
        ),
    ]
