# Generated by Django 4.1 on 2023-11-19 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("Analysis", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CollectionAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_time", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="CollectionWork",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_time", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="ColletionPackage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_time", models.DateTimeField(auto_now_add=True)),
                ("name", models.CharField(default="", max_length=100)),
                ("sum", models.IntegerField(default=0)),
                (
                    "anaylsis",
                    models.ManyToManyField(
                        blank=True,
                        related_name="collection_package_analysis",
                        through="Collection.CollectionAnalysis",
                        to="Analysis.analysis",
                    ),
                ),
            ],
        ),
    ]
