# Generated by Django 4.1 on 2023-11-19 03:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("Analysis", "0002_initial"),
        ("Collection", "0001_initial"),
        ("Essay", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="colletionpackage",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="colletionpackage",
            name="works",
            field=models.ManyToManyField(
                blank=True,
                related_name="collection_package_work",
                through="Collection.CollectionWork",
                to="Essay.work",
            ),
        ),
        migrations.AddField(
            model_name="collectionwork",
            name="collection_package",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="collectionpackage_work",
                to="Collection.colletionpackage",
            ),
        ),
        migrations.AddField(
            model_name="collectionwork",
            name="work",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="collection_work",
                to="Essay.work",
            ),
        ),
        migrations.AddField(
            model_name="collectionanalysis",
            name="analysis",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="collection_analysis",
                to="Analysis.analysis",
            ),
        ),
        migrations.AddField(
            model_name="collectionanalysis",
            name="collection_package",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="collectionpackage_analysis",
                to="Collection.colletionpackage",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="collectionwork",
            unique_together={("work", "collection_package")},
        ),
        migrations.AlterUniqueTogether(
            name="collectionanalysis",
            unique_together={("analysis", "collection_package")},
        ),
    ]
