# Generated by Django 4.2.4 on 2023-12-19 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_administrators',
            field=models.BooleanField(default=False),
        ),
    ]
