# Generated by Django 4.2.4 on 2023-12-20 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("UserManage", "0002_user_is_administrators"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avatar_url",
            field=models.CharField(default="", max_length=128, verbose_name="用户头像路径"),
        ),
    ]
