# Generated by Django 4.2.4 on 2023-12-22 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("UserManage", "0003_user_avatar_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_professional",
            field=models.IntegerField(default=-1, verbose_name="是否认证"),
        ),
    ]
