# Generated by Django 4.2.4 on 2023-12-23 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("UserManage", "0004_user_is_professional"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True, default="avatar/default.jpg", upload_to="data/avatar/"
            ),
        ),
    ]
