# Generated by Django 4.2.4 on 2023-12-23 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("UserManage", "0005_alter_user_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True, default="default.jpg", upload_to="data/avatar/"
            ),
        ),
    ]
