# Generated by Django 4.2.4 on 2023-12-26 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("UserManage", "0010_user_true_man_user_true_man_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="history",
            name="related_work_1",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="history",
            name="related_work_2",
            field=models.CharField(default="", max_length=255),
        ),
    ]
