# Generated by Django 4.1 on 2023-11-19 03:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("Essay", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("send_time", models.DateTimeField(auto_now_add=True)),
                ("type", models.IntegerField(default=0)),
                ("content", models.TextField(default="", max_length=1024)),
                ("reply", models.TextField(default="", max_length=1024)),
                ("pdf", models.CharField(default="", max_length=100)),
                ("url", models.CharField(default="", max_length=100)),
                (
                    "author",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="message_author",
                        to="Essay.author",
                    ),
                ),
                (
                    "institution",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="message_institution",
                        to="Essay.institution",
                    ),
                ),
            ],
        ),
    ]
