# Generated by Django 4.2.4 on 2023-12-22 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Message", "0003_message_analysis"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="is_read",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="message",
            name="open_alex_id",
            field=models.CharField(
                db_index=True,
                default="",
                max_length=200,
                verbose_name="对应作者的open_alex_id",
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="pdf",
            field=models.FileField(default="", upload_to="confirm/"),
        ),
    ]
