# Generated by Django 4.2.4 on 2023-12-23 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Message", "0004_message_is_read_message_open_alex_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="pdf",
            field=models.FileField(default="", upload_to="data/confirm/"),
        ),
    ]
