# Generated by Django 4.2.4 on 2023-12-23 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Message", "0005_alter_message_pdf"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="pdf",
            field=models.FileField(default="", upload_to="confirm/"),
        ),
    ]
