# Generated by Django 4.1 on 2023-11-19 03:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.IntegerField(default=0)),
                ("level", models.IntegerField(default=0)),
                ("created_time", models.DateTimeField(auto_now_add=True)),
                ("content", models.TextField(default="", max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name="CommentToAnalysis",
            fields=[
                (
                    "comment_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="Comment.comment",
                    ),
                ),
            ],
            bases=("Comment.comment",),
        ),
        migrations.CreateModel(
            name="CommentToComment",
            fields=[
                (
                    "comment_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="Comment.comment",
                    ),
                ),
            ],
            bases=("Comment.comment",),
        ),
        migrations.CreateModel(
            name="CommentToWork",
            fields=[
                (
                    "comment_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="Comment.comment",
                    ),
                ),
            ],
            bases=("Comment.comment",),
        ),
    ]
