# Generated by Django 4.1 on 2023-11-19 03:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("Analysis", "0002_initial"),
        ("Essay", "0001_initial"),
        ("Comment", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="replied_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="replied_user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="comment",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comment",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="commenttowork",
            name="work",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comment_to_work",
                to="Essay.work",
            ),
        ),
        migrations.AddField(
            model_name="commenttocomment",
            name="comment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comment_to_comment",
                to="Comment.comment",
            ),
        ),
        migrations.AddField(
            model_name="commenttocomment",
            name="father",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="Comment.comment",
            ),
        ),
        migrations.AddField(
            model_name="commenttoanalysis",
            name="analysis",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comment_to_analysis",
                to="Analysis.analysis",
            ),
        ),
    ]
