# Generated by Django 4.1 on 2023-11-19 03:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_professional",
                    models.IntegerField(default=-1, verbose_name="是否认证"),
                ),
                (
                    "open_alex_id",
                    models.CharField(
                        db_index=True,
                        default="",
                        max_length=200,
                        null=True,
                        verbose_name="对应的open_alex_id",
                    ),
                ),
                (
                    "real_name",
                    models.CharField(
                        db_index=True,
                        default="",
                        max_length=200,
                        null=True,
                        verbose_name="对应的作者真名",
                    ),
                ),
                ("work_count", models.IntegerField(default=0, verbose_name="作者作品数量")),
                (
                    "created_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "db_table": "Author",
            },
        ),
        migrations.CreateModel(
            name="Concept",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "open_alex_id",
                    models.CharField(
                        db_index=True,
                        default="",
                        max_length=200,
                        verbose_name="对应的open_alex_id",
                    ),
                ),
                ("cited_by_count", models.IntegerField(default=0)),
                ("descriptions", models.CharField(max_length=255, null=True)),
            ],
            options={
                "db_table": "Concept",
            },
        ),
        migrations.CreateModel(
            name="Institution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "open_alex_id",
                    models.CharField(
                        db_index=True,
                        default="",
                        max_length=200,
                        verbose_name="对应机构的open_alex_id",
                    ),
                ),
                ("country_code", models.CharField(max_length=200, null=True)),
                ("type", models.CharField(max_length=255, null=True)),
                ("work_count", models.IntegerField(default=0)),
                (
                    "created_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "db_table": "Institution",
            },
        ),
        migrations.CreateModel(
            name="Venue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "open_alex_id",
                    models.CharField(
                        db_index=True,
                        default="",
                        max_length=200,
                        verbose_name="对应Source的open_alex_id",
                    ),
                ),
                ("type", models.CharField(max_length=255, null=True)),
                ("work_count", models.IntegerField(default=0)),
                (
                    "created_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "db_table": "Venue",
            },
        ),
        migrations.CreateModel(
            name="Work",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "open_alex_id",
                    models.CharField(
                        db_index=True,
                        default="",
                        max_length=200,
                        verbose_name="对应作品的open_alex_id",
                    ),
                ),
                ("cited_by_count", models.IntegerField(default=0)),
                ("display_name", models.CharField(max_length=255, null=True)),
                ("doi", models.CharField(max_length=255, null=True)),
                ("language", models.CharField(max_length=255, null=True)),
                ("title", models.CharField(max_length=255, null=True)),
                ("type", models.CharField(max_length=255, null=True)),
                (
                    "created_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Essay.author"
                    ),
                ),
                (
                    "venue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Essay.venue"
                    ),
                ),
            ],
            options={
                "db_table": "Works",
            },
        ),
        migrations.CreateModel(
            name="Year",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField(default=0)),
                ("works", models.IntegerField(default=0, verbose_name="论文数")),
                ("cited", models.IntegerField(default=0, verbose_name="被引用数")),
                (
                    "concept",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Essay.concept",
                    ),
                ),
                (
                    "institution",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Essay.institution",
                    ),
                ),
                (
                    "venue",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Essay.venue",
                    ),
                ),
                (
                    "work",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Essay.work",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="author",
            name="institution",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Essay.institution",
            ),
        ),
    ]
