# Generated by Django 4.1 on 2023-11-18 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Essay", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="institution",
            old_name="worksCount",
            new_name="work_count",
        ),
        migrations.RenameField(
            model_name="venue",
            old_name="worksCount",
            new_name="work_count",
        ),
    ]
