# Generated by Django 4.2.4 on 2023-12-20 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Essay", "0002_work_author_display_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="work",
            name="author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Essay.author",
            ),
        ),
        migrations.AlterField(
            model_name="work",
            name="venue",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Essay.venue",
            ),
        ),
    ]
