# Generated by Django 4.2.4 on 2023-12-22 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Essay", "0003_alter_work_author_alter_work_venue"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="author",
            name="is_professional",
        ),
        migrations.AddField(
            model_name="author",
            name="institution_display_name",
            field=models.CharField(
                db_index=True,
                default="",
                max_length=200,
                null=True,
                verbose_name="对应的机构名称",
            ),
        ),
    ]
